import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainLayout from "./(main)/layout";
import { ViewAreaProvider } from "@/components/providers/view-area-provider";

const geistSans = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
	subsets: ["latin"],
	variable: "--font-geist-mono",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="bg-[black]">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-[black]`}>
				<ViewAreaProvider className="relative mx-auto min-h-screen w-full max-w-xl overflow-hidden bg-[white]">
					<MainLayout>{children}</MainLayout>
				</ViewAreaProvider>
			</body>
		</html>
	);
}
