import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import vaylaLogo from "@/assets/images/vayla-logo.png";
import { PrivyAuthProvider } from "@/share/components/providers/privy-provider";
import { QueryProvider } from "@/share/components/providers/query-provider";
import "@/styles/globals.css";

const geistSans = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
	subsets: ["latin"],
	variable: "--font-geist-mono",
});

export const metadata: Metadata = {
	title: "Vayla Arena",
	description: "Generated by create next app",
	icons: {
		icon: [{ url: vaylaLogo.src, type: "image/png" }],
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-[black]`}
			>
				<PrivyAuthProvider>
					<QueryProvider>{children}</QueryProvider>
				</PrivyAuthProvider>
			</body>
		</html>
	);
}
